version: 2
jobs:
  test:
    docker:
      - image: "circleci/node:12.16"
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}'
      - run:
          name: Install node modules
          command: npm ci
      - save_cache:
          key: 'dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run coverage
      - run:
          name: Codecov
          command: "bash <(curl -s https://codecov.io/bash)"
workflows:
  version: 2
  test:
    jobs:
      - test
